default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USERNAME_LOCAL'] %>
  password: <%= ENV['POSTGRES_PASSWORD_LOCAL'] %>
  host: localhost
  port: 5432
  database: terrier_rails_assessment_db

development:
  <<: *default

test:
  <<: *default

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_DB'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

  cable:
    adapter: postgresql
    database: <%= ENV['POSTGRES_DB'] %> # Same database as main app
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: <%= ENV['POSTGRES_HOST'] %>
    pool: 5
